version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production